spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to My cards related QA APIs "
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "{cipher}b41c10aed25b3428c86c70869c5f70839a0a30462d95ff78925db72f4f0662d02808527e5d7dcac0e10c6377678df184"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267