spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to My loans related prod APIs "
  contactDetails:
    name: "Pelias Sudhir - Product Owner"
    email: "{cipher}38ff96a5a9dc0944ede8f51c96919c2a0adcdf845ab099785f8815d4696da03d6fd92f067156b3848105936fd7230b9c"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956