spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to My loans related QA APIs "
  contactDetails:
    name: "Cyrano Marita - QA Lead"
    email: "{cipher}5913fb67483b124fe8ccc2c26c075a59b7e95ddd4229ab63c955f4ee050ed79fb555f8ed02a0be30b858835d3a9a6ed2"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467